Allocator
timtibilov/HSE-Course pull request #5
Opened 2021-06-04 07:56 UTC by timtibilov

Немного изменил CMakeFile.txt, так как даже с добавленной ссылкой на Clang-Format в ENV как переменная среды проект почему-то не хотел собираться :(

2021-06-04 08:06 UTC, timtibilov commented
Не знаю, почему чекер не смог собрать проект, у меня все собралось, и тесты прошли
![image](https://user-images.githubusercontent.com/44522301/120768524-e9fb7f00-c524-11eb-9aa7-90bd488701d6.png)

2021-06-04 08:07 UTC, timtibilov commented
![image](https://user-images.githubusercontent.com/44522301/120768686-17e0c380-c525-11eb-8a0e-6209d06eb923.png)

2021-06-04 12:32 UTC, Costello1329 requested changes
В целом – хорошо!
Давайте всем методам добавим корректные noexcept спецификации, и будет отлично!

2021-06-04 12:32 UTC, Costello1329 commented on module-1/homework/Allocator/src/allocator/allocator.h
> +// Realized by Taimuraz Tibilov, based on Linear Allocator principle
> Realized
Implemented, все же))

2021-06-04 12:32 UTC, Costello1329 commented on module-1/homework/Allocator/src/allocator/allocator.h
> +CustomAllocator<T>::CustomAllocator(const CustomAllocator& other) noexcept :
А зачем вообще эта специализация, если есть общая версия copy ctor?

2021-06-04 12:32 UTC, Costello1329 commented on module-1/homework/Allocator/src/allocator/allocator.h
> +    (*_ref_count)--;
Можно было запихнуть это действие прямо в условие if:

if (--(*_ref_count) == 0) {
  ...
}

2021-06-04 12:32 UTC, Costello1329 commented on module-1/homework/Allocator/src/allocator/allocator.h
> +T* CustomAllocator<T>::allocate(std::size_t n) throw (std::bad_alloc) {
throw – устарел. Не рекомендую его использовать. Может стоит заменить на noexcept(false) ?

2021-06-04 12:32 UTC, Costello1329 commented on module-1/homework/Allocator/src/allocator/allocator.h
> +void CustomAllocator<T>::destroy(CustomAllocator::pointer p) {
Хорошо бы добавить noecept-спецификацию

2021-06-04 14:57 UTC, timtibilov commented on module-1/homework/Allocator/src/allocator/allocator.h
> +CustomAllocator<T>::CustomAllocator(const CustomAllocator& other) noexcept :
Если честно - не знаю, так было в шаблоне задания)

2021-06-04 15:05 UTC, timtibilov commented on module-1/homework/Allocator/src/allocator/allocator.h
> +T* CustomAllocator<T>::allocate(std::size_t n) throw (std::bad_alloc) {
Я решил сделать тогда no guarantee

2021-06-07 04:56 UTC, Costello1329 requested changes

2021-06-07 04:56 UTC, Costello1329 commented on module-1/homework/Allocator/src/allocator/allocator.h
> +    void destroy(pointer p) noexcept;
ну а если вдруг деструктор T – не noexcept?
Знаете про std::is_nothrow_destructible?

2021-06-07 04:56 UTC, Costello1329 commented on module-1/homework/Allocator/src/allocator/allocator.h
>          throw (std::bad_alloc());
А зачем тут скобки? не ставьте их тут никогда.
`(...)` – не то же самое, что и `...`, помните это.

2021-06-07 04:56 UTC, Costello1329 commented on module-1/homework/Allocator/src/allocator/allocator.h
>      void construct(pointer p, Args&&... args);
Можно добавить conditional noexcept-спецификацию.
Вы знаете про std::is_nothrow_constructible?

2021-06-07 07:48 UTC, Costello1329 requested changes

2021-06-07 07:48 UTC, Costello1329 commented on module-1/homework/Allocator/src/allocator/allocator.h
> +    void construct(pointer p, Args&&... args) noexcept(std::is_nothrow_constructible<value_type>::value);
Во-первых, есть is_nothrow_constructible_v,
Во-вторых, тут вы проверяете на наличие default ctor, когда надо проверять на наличие ctor из пака аргументов args

2021-06-07 07:48 UTC, Costello1329 commented on module-1/homework/Allocator/src/allocator/allocator.h
> +    void destroy(pointer p) noexcept(std::is_nothrow_destructible<value_type>::value);
is_nothrow_destructible -> is_nothrow_destructible_v

2021-06-08 16:19 UTC, Costello1329 approved these changes

2021-06-08 16:19 UTC, merged